# name: GitHub Actions Demo
name: Deployment 🚀
# run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
run-name: Build & Deploy 🚀 ${{ inputs.deploy_target }}
# on: [push]
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Explore-GitHub-Actions:
  Build-Deploy-Actions:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      ##
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event. 🎉"
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub! 🐧"

      # Test mupltiline text
      # - run: >- echo "Branch: ${{ github.ref }} in repository ${{ github.repository }}. 🔎 "
      - run: echo "Branch ${{ github.ref }} in repository ${{ github.repository }}. 🔎 "

      - name: Deploy PR Preview
        # You may pin to the exact commit or the version.
        # uses: rossjrw/pr-preview-action@9dac5c4777c535516ebf819f93aeadac70f66488

        uses: rossjrw/pr-preview-action@v1.3.0
        with:
          # Branch on which the previews will be deployed.
          preview-branch: # optional, default is gh-pages
          # Name of the directory containing all previews.
          umbrella-dir: # optional, default is pr-preview
          # Directory containing files to deploy.
          source-dir: # optional, default is .
          # Custom pages URL
          custom-url: # optional, default is
          # Determines what this action will do when it is executed. Supported values: `deploy`, `remove`, `auto` (default).
          # If set to `deploy`, will attempt to deploy the preview and overwrite any existing preview in that location.
          # If set to `remove`, will attempt to remove the preview in that location.
          # If set to `auto`, the action will try to determine whether to deploy or remove the preview. It will deploy the preview on `pull_request.types.synchronize` and `.opened` events, and remove it on `pull_request.types.closed` events. It will not do anything for all other events. `auto` is the default value.
          action: # optional, default is auto
      # Runner PostTest
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          - run: echo "🍏 This job's status is ${{ job.status }}."
